### ISSUE TITLE
Gas optimizations across the whole repo

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/AssemblyPress#72]
I am not an optimizoooor whatsoever. I imagine there are tons of optimizations to be found all over the place, in addition to redundant logic or overzealous zero checks that dont need to be there

**Comment by salieflewis** [comment]
I'm proposing that we close this issue in favor of moving this topic to a [discussion](https://github.com/public-assembly/AssemblyPress/discussions/78).
