### ISSUE TITLE
Remove the unused function parameter tokenId in CurationLogic

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/AssemblyPress#82]
Similar to issue #81, the `canBurn` function takes a `tokenId` where it is not being used. Link to snippet is [here](https://github.com/public-assembly/AssemblyPress/blob/d557f45cdd6dca8fc9de4dee5857e41cfc4027db/src/token/ERC721/strategies/curation/logic/CurationLogic.sol#L147C1-L162).

A pull request surrounding this issue should also correct the [typo on line 147](https://github.com/public-assembly/AssemblyPress/blob/d557f45cdd6dca8fc9de4dee5857e41cfc4027db/src/token/ERC721/strategies/curation/logic/CurationLogic.sol#L147).

Additionally, a pull request should eliminate the [redundancy in the comment on line 156](https://github.com/public-assembly/AssemblyPress/blob/d557f45cdd6dca8fc9de4dee5857e41cfc4027db/src/token/ERC721/strategies/curation/logic/CurationLogic.sol#L156).

**Comment by ujwalkumar1995** [comment]
Hey @salieflewis 
Can I work on fixing these?
Also should I submit separate PR for these issues or should I do it as part of a single PR?

**Comment by salieflewis** [comment]
Hi @ujwalkumar1995. I just spoke to @0xTranqui about why those arguments exist there in the first place. The reason is so that the functions adhere to the interface defined in [IERC721PressLogic](https://github.com/public-assembly/AssemblyPress/blob/main/src/token/ERC721/core/interfaces/IERC721PressLogic.sol). See [line 22](https://github.com/public-assembly/AssemblyPress/blob/d557f45cdd6dca8fc9de4dee5857e41cfc4027db/src/token/ERC721/core/interfaces/IERC721PressLogic.sol#L22).

So while it is not relevant int he context of this CurationLogic contract, it exists in order to keep the standards of the interface. 

That being said, I think that this should be clarified in the natspec, with a @dev tag! So to answer your question, yes you can work on these, and one PR featuring everything described in this issue, as well as what is outlined in #81, would be awesome!

**Comment by ujwalkumar1995** [comment]
Hey @salieflewis 
Thank you for the reply. So as per my understanding we can remove this unused param both from the interface and the actual method. Also same will apply for issue #81.
Please confirm if this is correct.

**Comment by salieflewis** [comment]
Unfortunately no. Even though the param is unused in the CurationLogic implementation, it could potentially be used by another logic implementation that adheres to IERC721PressLogic. And because ICurationLogic adheres to IERC721PressLogic the function signature should remain as is!

**Comment by salieflewis** [comment]
Resolved in #88
